#!/bin/bash
declare -a campuses=("cgu" "cmc" "hmc" "kecksci" "kgi" "pit" "pom" "scr")
mmYYYY=$(date +%Y%m)
fullfile=$1
filename="${fullfile%.*}"
for campus in ${campuses[*]}
    do
        campusfile=$filename"_"$campus".rpt"
        head -n $(grep -n Login\ summary $1 |cut -d: -f1) $fullfile |grep $campus > $campusfile
    done
